### PR TITLE
Pull Request - 1: HwMap, Field-Centric Drive, and TeleOp Classes

### PR DESCRIPTION
**Pull request by Vivaan-crypto**
This is the PR for making the HwMap and Controller class available for the whole repository. This will help everyone who creates a new branch to start with those 2 core files.

### CODE REVIEW

**Comment by joseph62** [comment]
Hey All,

It was great to meet you all today!

I wanted to give a summary of the discussion we had today regarding this PR. 

### Pull Request Descriptions
The above comment does provide a generic description of what this pull request accomplishes, however it is a good idea to provide slightly more specific description so that pull request reviewers have proper context. As an example you might say:
> The changes in this pull request include the HwMap to allow for consistent access to attached devices as well as the Controller which allows for controller inputs to be accessed in a uniform way.

You can also include mentions of particular choices that you made which might be worth additional discussion or consideration:
> I decided against adding traditional getter and setter methods to the Controller class due to the volume of attributes

### Controller Class Structure
Currently the Controller class contains duplicated variables for both gamepads like `gamepad1LBumper` and `gamepad2LBumper`. It might be cleaner to further organize those controller specific data points into something like a `Gamepad` class.
```
public class Gamepad {
  private boolean a;
  private boolean b;
  private boolean x;
  private boolean y;
  // remaining code omitted
}
```
This would allow the current Controller class to have an attribute per game pad so you can reference the values like `controller.gamepadOne.leftBumper`. 

### Meaningful Commit Messages
This was not discussed today, but I figured it would still be worthwhile to note. It is a good practice to provide meaningful messages for git commits. For the 7e2b0cd7ea6a85e23961b69169dec635232fcc68 commit I might include a message like 
> Create HwMap and Controller classes

while the 8889ea51d86d32d450cfddb30cad119d1c6ffd42 commit might be something like
> Swap ButtonReader usage in Controller with simple boolean values

Remember that commit messages should be relatively short. It is a bit of an art to maintain the balance between informational and brief.

**Comment by Raven498** [comment]
Tested along with FieldCentricDrive (FTCLib version) + made following changes after testing:
1. Removed inheritance from HWMapFTCLib for FieldCentricDriveFTCLib (was causing a null object error + it was unnecessary)
2. Moved all FieldCentric hardware init code to HWMap instead of HWMapFTCLib (basically, removed all hardware except for drive motors)
    - HWMapFTCLib now contains hardware init for test bench while HWMap contains hardware init for FieldCentric drive - need to rename to make distinction clearer
3. (In HWMap): Added inverse statements for each motor used on FieldCentric drivetrain - may be different depending on the motors currently being used
4. (In HWMap): Conducted odo retraction during FieldCentric init - make sure retraction actually occurs when testing FieldCentric
5. **TLDR: Controller class was fine, but HWMap required some changes w/ FieldCentric**

Next steps:
- Still need to test Controller button handling on test bench - will close PR after this is done

**Review by Vivaan-crypto — COMMENTED** [review]
These files have been reviewed and I've seen that these files work

**Comment by Raven498** [comment]
New changes
1. Decided to remove Controller class by consensus of programming team
2. Removed odo retraction + HWMapFTCLib - not needed for master

**Review by Raven498 — APPROVED** [review]
Adapted HWMap w/ FieldCentric drivetrain
Tested FieldCentric w/ HWMap on last year's robot - works well
Decided to remove Controller following consensus

**Pull request merged**
